name: Release

on:
  push:
    branches:
      - 'dev*'

jobs:

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install yq
        run: |
          VERSION=v4.34.1
          BINARY=yq_linux_amd64
          curl -Lo yq https://github.com/mikefarah/yq/releases/download/$VERSION/$BINARY && chmod +x yq

      - name: package helm chart
        run: | 
          helm registry login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
          helm package --dependency-update .

      - name: package helm chart
        run: | 
          helm show chart .
          CHART_NAME=$(helm show chart . | ./yq -r .name)
          CHART_VERSION=$(helm show chart . | ./yq -r .version)
          helm push ./$CHART_NAME-$CHART_VERSION.tgz oci://${{ secrets.REGISTRY_URL }}/charts